# -*- coding: utf-8 -*-
"""PRO_C106_Solución

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ifinTaePaOa_qDUQq_GjMD0wTSUXNcFk

###Crea una lista llamada **result** que tenga los siguientes elementos:
* “Matemáticas”
* 90
* “Inglés”
* 80
* “Historia”
* 75
* “Arte”
* 85
"""

result = [ "Matemáticas",
"90",
"Inglés",
"80",
"Historia",
"75",
"Arte",
"85" ] 
result

"""### Utiliza el operador slice para imprimir solo los nombres de las materias"""

result[0 :8 :2 ]

"""### Utiliza el operador slice para imprimir solo las calificaciones"""

result[1 : 8: 2 ]